import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import type { ReactNode } from "react";
import { defaultThemes } from "../theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mockLoginUserA = {
  theme: "darkBlue",
};

export default function RootLayout({
  children,
}: {
  readonly children: ReactNode;
}): JSX.Element {
  const userTheme = defaultThemes.find(
    (defaultTheme) => defaultTheme.id === mockLoginUserA.theme,
  );

  return (
    <html
      lang="en"
      suppressHydrationWarning
      style={
        userTheme
          ? {
              colorScheme: userTheme.colorSchema,
              // eslint-disable-next-line unicorn/no-array-reduce, unicorn/prefer-object-from-entries
              ...Object.entries(userTheme.cssVariables).reduce(
                (acc, [key, value]) => ({ ...acc, [key]: value }),
                {},
              ),
            }
          : undefined
      }
    >
      <body className={inter.className}>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
