name: Terraform Plan

on:
  workflow_dispatch:
  push:
  pull_request:

# TODO: packages-main/infra配下に変更があった時のにに実行させる

env:
  TF_VERSION: 1.6.6

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan-staging:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    environment: staging
    steps:
      ############## Setup

      - uses: actions/checkout@v4

      - name: "Authenticate with Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_MAIN_SERVICE_ACCOUNT_EMAIL }}

      - name: "Setup gcloud CLI"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_TEAM_TOKEN }}
          # below is workaround for issue https://github.com/hashicorp/setup-terraform/issues/152
          terraform_wrapper: false

      - name: Setup tfcmt
        uses: shmokmt/actions-setup-tfcmt@v2
        with:
          version: v4.6.0

      ############## Execute

      - name: Terraform Init
        working-directory: packages-main/infra
        run: make init-stag

      - name: Terraform plan
        working-directory: packages-main/infra/environments/staging
        run: tfcmt plan -patch -- terraform plan -no-color -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
